version: "3.8"

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db
    env_file:
      - ./secrets/.env
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8083:8083"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-db:27017/admin?authSource=admin
    depends_on:
      - mongo-db
    networks:
      - mongo-network
  
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: ["--verbose", "--global-response-templating"]

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
